local buffer = require("color.buffer")
local highlight = require("color.highlight")

local ns = vim.api.nvim_create_namespace("color")

local function make_buf(lines)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  return buf
end

local function get_extmarks(buf)
  return vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, { details = true })
end

describe("buffer", function()
  local opts = { RRGGBB = true, RGB = true, names = false, mode = "background", lsp = false }

  before_each(function()
    highlight.clear_cache()
  end)

  after_each(function()
    for _, b in ipairs(vim.api.nvim_list_bufs()) do
      if buffer.is_attached(b) then
        buffer.detach(b)
      end
    end
  end)

  describe("attach/detach", function()
    it("attaches and creates extmarks", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, opts)
      assert.is_true(buffer.is_attached(buf))
      local marks = get_extmarks(buf)
      assert.is_true(#marks > 0)
    end)

    it("detach clears extmarks", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, opts)
      buffer.detach(buf)
      assert.is_false(buffer.is_attached(buf))
      local marks = get_extmarks(buf)
      assert.are.equal(0, #marks)
    end)

    it("double attach is idempotent", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, opts)
      buffer.attach(buf, opts)
      assert.is_true(buffer.is_attached(buf))
    end)

    it("detach on unattached is safe", function()
      local buf = make_buf({ "hello" })
      assert.has_no.error(function()
        buffer.detach(buf)
      end)
    end)
  end)

  describe("toggle", function()
    it("attaches when not attached", function()
      local buf = make_buf({ "#00ff00" })
      buffer.toggle(buf, opts)
      assert.is_true(buffer.is_attached(buf))
    end)

    it("detaches when attached", function()
      local buf = make_buf({ "#00ff00" })
      buffer.attach(buf, opts)
      buffer.toggle(buf, opts)
      assert.is_false(buffer.is_attached(buf))
    end)
  end)

  describe("highlighting", function()
    it("highlights RRGGBB colors", function()
      local buf = make_buf({ "color: #ff0000;" })
      buffer.attach(buf, opts)
      local marks = get_extmarks(buf)
      assert.are.equal(1, #marks)
    end)

    it("highlights multiple colors on same line", function()
      local buf = make_buf({ "#aabbcc #112233" })
      buffer.attach(buf, opts)
      local marks = get_extmarks(buf)
      assert.are.equal(2, #marks)
    end)

    it("highlights across multiple lines", function()
      local buf = make_buf({ "#ff0000", "plain text", "#00ff00" })
      buffer.attach(buf, opts)
      local marks = get_extmarks(buf)
      assert.are.equal(2, #marks)
    end)

    it("no extmarks on plain text", function()
      local buf = make_buf({ "no colors here" })
      buffer.attach(buf, opts)
      local marks = get_extmarks(buf)
      assert.are.equal(0, #marks)
    end)

    it("respects RGB option", function()
      local buf = make_buf({ "#f0a" })
      buffer.attach(buf, vim.tbl_extend("force", opts, { RGB = true }))
      local marks = get_extmarks(buf)
      assert.are.equal(1, #marks)
    end)
  end)

  describe("reload", function()
    it("refreshes single buffer", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, opts)
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "#00ff00" })
      buffer.reload(buf, opts)
      local marks = get_extmarks(buf)
      assert.are.equal(1, #marks)
    end)

    it("reload nil refreshes all attached buffers", function()
      local buf1 = make_buf({ "#ff0000" })
      local buf2 = make_buf({ "#00ff00" })
      buffer.attach(buf1, opts)
      buffer.attach(buf2, opts)
      buffer.reload(nil, opts)
      assert.is_true(#get_extmarks(buf1) > 0)
      assert.is_true(#get_extmarks(buf2) > 0)
    end)

    it("reload on unattached buffer is no-op", function()
      local buf = make_buf({ "#ff0000" })
      assert.has_no.error(function()
        buffer.reload(buf, opts)
      end)
    end)
  end)

  describe("mode variations", function()
    it("foreground mode creates extmarks", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, vim.tbl_extend("force", opts, { mode = "foreground" }))
      local marks = get_extmarks(buf)
      assert.are.equal(1, #marks)
    end)

    it("virtualtext mode creates extmarks", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, vim.tbl_extend("force", opts, { mode = "virtualtext" }))
      local marks = get_extmarks(buf)
      assert.are.equal(1, #marks)
    end)

    it("multiple modes create multiple extmarks per color", function()
      local buf = make_buf({ "#ff0000" })
      buffer.attach(buf, vim.tbl_extend("force", opts, { mode = { "background", "virtualtext" } }))
      local marks = get_extmarks(buf)
      assert.are.equal(2, #marks)
    end)
  end)
end)
