local highlight = require("iro.highlight")

describe("highlight", function()
  before_each(function()
    highlight.clear_cache()
  end)

  describe("ensure", function()
    it("returns hl group name for background mode", function()
      local name = highlight.ensure("ff0000", "background")
      assert.are.equal("iro_background_ff0000", name)
    end)

    it("returns hl group name for foreground mode", function()
      local name = highlight.ensure("00ff00", "foreground")
      assert.are.equal("iro_foreground_00ff00", name)
    end)

    it("returns hl group name for virtualtext mode", function()
      local name = highlight.ensure("0000ff", "virtualtext")
      assert.are.equal("iro_virtualtext_0000ff", name)
    end)

    it("caches hl group", function()
      local name1 = highlight.ensure("ff0000", "background")
      local name2 = highlight.ensure("ff0000", "background")
      assert.are.equal(name1, name2)
    end)

    it("different modes produce different groups", function()
      local bg = highlight.ensure("ff0000", "background")
      local fg = highlight.ensure("ff0000", "foreground")
      assert.are_not.equal(bg, fg)
    end)

    it("creates nvim highlight", function()
      highlight.ensure("ff0000", "background")
      local hl = vim.api.nvim_get_hl(0, { name = "iro_background_ff0000" })
      assert.is_not_nil(hl.bg)
    end)

    it("dark color has fg set on background mode", function()
      highlight.ensure("000000", "background")
      local hl = vim.api.nvim_get_hl(0, { name = "iro_background_000000" })
      assert.is_not_nil(hl.fg)
    end)

    it("light color gets black fg on background mode", function()
      highlight.ensure("ffffff", "background")
      local hl = vim.api.nvim_get_hl(0, { name = "iro_background_ffffff" })
      assert.are.equal(0x000000, hl.fg)
    end)
  end)

  describe("alpha blending", function()
    it("blends with editor bg when alpha provided", function()
      highlight.set_editor_bg("#ffffff")
      highlight.clear_cache()
      local name = highlight.ensure("000000", "background", 0.5)
      assert.is_truthy(name:find("^iro_"))
      local hl = vim.api.nvim_get_hl(0, { name = name })
      assert.is_not_nil(hl.bg)
      local bg_r = bit.rshift(hl.bg, 16)
      local bg_g = bit.band(bit.rshift(hl.bg, 8), 0xff)
      local bg_b = bit.band(hl.bg, 0xff)
      assert.is_true(bg_r >= 120 and bg_r <= 135)
      assert.is_true(bg_g >= 120 and bg_g <= 135)
      assert.is_true(bg_b >= 120 and bg_b <= 135)
    end)

    it("alpha 1 produces original color", function()
      highlight.set_editor_bg("#ffffff")
      highlight.clear_cache()
      local name = highlight.ensure("ff0000", "background", 1)
      local hl = vim.api.nvim_get_hl(0, { name = name })
      assert.are.equal(0xff0000, hl.bg)
    end)

    it("alpha nil uses original color", function()
      highlight.clear_cache()
      local name = highlight.ensure("ff0000", "background", nil)
      local hl = vim.api.nvim_get_hl(0, { name = name })
      assert.are.equal(0xff0000, hl.bg)
    end)

    it("different alpha produces different cache key", function()
      highlight.set_editor_bg("#000000")
      highlight.clear_cache()
      local n1 = highlight.ensure("ff0000", "background", 0.3)
      local n2 = highlight.ensure("ff0000", "background", 0.8)
      assert.are_not.equal(n1, n2)
    end)
  end)

  describe("clear_cache", function()
    it("resets cache so new hl groups are created", function()
      highlight.ensure("aabbcc", "background")
      highlight.clear_cache()
      local name = highlight.ensure("aabbcc", "background")
      assert.are.equal("iro_background_aabbcc", name)
    end)
  end)

  describe("set_editor_bg", function()
    it("accepts hex string", function()
      assert.has_no.error(function()
        highlight.set_editor_bg("#1e1e1e")
      end)
    end)

    it("accepts nil", function()
      assert.has_no.error(function()
        highlight.set_editor_bg(nil)
      end)
    end)
  end)
end)
